List<String> dataKlinik = [
  "Klinik Asih Usadha",
  "Bali 911 Dental Clinic",
  "Klinik Pratama Rawat Jalan Bali Nusa Medika",
  "Klinik Utama Bali Puri Medika",
  "Barta Medika Clinic",
  "Klinik Pratama Rawat Jalan Bhaksena IDT",
  "Klinik Bhayangkara Polda Bali",
  "Klinik Bhayangkara Polresta Denpasar",
  "Klinik Bhayangkara Satbrimobda Bali",
  "Klinik Bina Usada",
  "Klinik Pratama Rawat Jalan BNN Provinsi Bali",
  "BRAIA Klinik Spesialis Kulit dan Kelamin",
  "Klinik Utama Bunga Emas",
  "Klinik Utama Dharma Sidhi",
  "Klinik Pratama EastWest",
  "FKTP Kepaon",
  "FKTP Makodam",
  "Klinik Pratama Rawat Jalan FKTP Sudirman",
  "Klinik Karya Prima",
  "Klinik Kimia Farma Sanur",
  "Lumi Clinic",
  "Klinik Mesari Usadha",
  "Klinik Merdeka Medical Centre",
  "Klinik Utama Niki Diagnostic Center",
  "Klinik Omsa Medic",
  "Klinik Osadha",
  "Klinik Utama Padma Bahtera Medical Centre",
  "Klinik Pedungan Medika",
  "Klinik Penta Medica ",
  "Klinik Pratama Rawat Inap Petanu Medical Center",
  "Klinik Remedium Care",
  "Klinik Utama Rawat Inap Sari Dharma",
  "Klinik Semesta Mandiri",
  "Klinik Smile Medical Centre",
  "Klinik Sudi Santhi",
  "Klinik Sudirman Medical Centre",
  "Klinik Pratama TPKK Denpasar",
  "Klinik Utama Tulus Ayu",
  "Klinik Pratama Warmadewa",
  "Klinik Werdhi Ayu",
  "Klinik Widya Medika",
  "Klinik Pratama Rawat Inap Wiratni",
  "Klinik Utama WM Medika",
  "Klinik KF. No. 034 Diponegoro",
  "Sanur Medical Clinic",
  "Klinik Pratama SOS GatotKaca",
  "SOS Medika Klinik Bali",
  "Klinik Pratama Wirati",
  "Klinik Anugerah",
  "Klinik Utama Bali Husada Cipta Canthi",
  "Klinik Pratama Dental Rejuvie",
  "Klinik Utama Rejuvie Sanur",
  "Klinik Utama Rawat Inap Arta Bunda",
  "Klinik Utama Quantum",
  "Klinik Catur Warga",
  "BK Lanal Denpasar",
  "Klinik Bali Sudirman Medical Centre",
  "Klinik BRIMEDIKA Cabang Denpasar",
  "O Smile Laser Dental Centre",
  "Klinik Graha Medika",
  "Klinik Utama Be Health Medika",
  "Naavagreen Natural Skin Care",
  "Aira Skin Clinic",
  "Kusuma Beauty Clinic",
  "Klinik Kecantikan Estetika Larissa",
  "Klinik Kecantikan House Of Dura",
  "EMWE Clinic ",
  "Indivara Aesthetic",
  "Ria Klinik Kecantikan",
  "UP. Altara",
  "Natasha Skin Care",
  "Natasha Skin Care Renon",
  "Mulya Aesthetic Clinic",
  "The Emdee Skin Clinic",
  "Klinik Kecantikan Aishwarya",
  "PT. Bali Sano Utama",
  "Olivia Slimming and Skincare",
  "Erha Clinic",
  "D & I Skin Center Klinik Kesehatan",
  "D & I Skin Center Klinik Kesehatan",
  "D N I Skin Centre",
  "D N I Skin Care",
  "Klinik Kecantikan W G",
  "BELLADONNA",
  "Klinik Estetika dr. Affandi",
  "AKL CLINIC",
  "Ms Glow Aesthetic Clinic ",
  "Awe Beauty Clinic",
  "L'Viors Clinic",
  "Divine Clinic",
  "Manika Aesthetic Clinic",
  "Klinik Wijaya Platinum"
];

List<String> dataRumahSakit = [
  "RS Bali Royal",
  "RS Balimed",
  "RS Bhakti Rahayu",
  "RS Bhayangkara Denpasar",
  "RS Dharma Yadnya",
  "RS Kasih Ibu General Hospital",
  "RS Manuaba",
  "RS Mata Bali Mandara",
  "RS Prima Medika",
  "RS Puri Raharja",
  "RS Ramata",
  "RS Surya Husadha Denpasar",
  "RS Surya Husadha Ubung",
  "RSAD Udayana",
  "RSGM Universitas Mahasaraswati",
  "RSIA Harapan Bunda",
  "RSIA Pucuk Permata Hati",
  "RSIA Puri Bunda Denpasar",
  "RSPTN Udayana",
  "RSU Bali Jimbaran",
  "RSUD Bali Mandara",
  "RSUD Wangaya",
  "RSUP Sanglah Denpasar"
];

List<String> dataPuskesmas = [
  "Puskesmas I Denpasar Utara",
  "Puskesmas II Denpasar Utara",
  "Puskesmas III Denpasar Utara",
  "Puskesmas I Denpasar Barat",
  "Puskesmas II Denpasar Barat",
  "Puskesmas I Denpasar Selatan",
  "Puskesmas II Denpasar Selatan",
  "Puskesmas III Denpasar Selatan",
  "Puskesmas IV Denpasar Selatan",
  "Puskesmas I Denpasar Timur",
  "Puskesmas II Denpasar Timur"
];

List<String> dataAntibiotik = [
  "Aldesulfone sodium",
  "Amikacin",
  "Aminosalicylate",
  "Amoxicillin",
  "Amoxicillin-Clavulanic-acid",
  "Ampicillin",
  "Ampicillin-sulbactam",
  "Apramycin",
  "Arbekacin",
  "Astromicin",
  "Avoparcin",
  "Azidocillin",
  "Azithromycin",
  "Azlocillin",
  "Aztreonam",
  "Bacampicillin",
  "Bacitracin",
  "Bedaquiline",
  "Bekanamycin",
  "Benethamine-Benzylpenicillin",
  "Benzathine-Benzylpenicillin",
  "Benzylpenicillin/Penicillin G",
  "Besifloxacin",
  "Biapenem",
  "Brodimoprim",
  "Cadazolid",
  "Calcium",
  "Capreomycin",
  "Carbenicillin",
  "Carindacillin",
  "Carumonam",
  "Cefacetrile",
  "Cefaclor",
  "Cefadroxil",
  "Cefalexin",
  "Cefalonium",
  "Cefaloridine",
  "Cefalotin",
  "Cefalotin",
  "Cefamandole",
  "Cefapirin",
  "Cefatrizine",
  "Cefazedone",
  "Cefazolin",
  "Cefbuperazone",
  "Cefcapene",
  "Cefdinir",
  "Cefditoren",
  "Cefepime",
  "Cefetamet",
  "Cefixime",
  "Cefmenoxime",
  "Cefmetazole",
  "Cefminox",
  "Cefodizime",
  "Cefonicid",
  "Cefoperazone",
  "Cefoperazone-sulbactam",
  "Ceforanide",
  "Cefoselis",
  "Cefotaxime",
  "Cefotetan",
  "Cefotiam",
  "Cefovecin",
  "Cefoxitin",
  "Cefozopran",
  "Cefpiramide",
  "Cefpirome",
  "Cefpodoxime",
  "Cefprozil",
  "Cefquinome",
  "Cefradine",
  "Cefroxadine",
  "Cefsulodin",
  "Ceftaroline",
  "Ceftazidime",
  "Ceftazidime-avibactam",
  "Ceftezole",
  "Ceftibuten",
  "Ceftiofur",
  "Ceftizoxime",
  "Ceftobiprole",
  "Ceftolozane",
  "Ceftriaxone",
  "Ceftriaxone-sulbactam",
  "Cefuroxime",
  "Cethromycin",
  "Chloramphenicol",
  "Chlortetracycline",
  "Cinoxacin",
  "Ciprofloxacin",
  "Clarithromycin",
  "Clindamycin",
  "Clofazimine",
  "Clometocillin",
  "Clomocycline",
  "Cloxacillin",
  "Colistin",
  "Cycloserine",
  "Dalbavancin",
  "Danofloxacin",
  "Dapsone",
  "Daptomycin",
  "Delafloxacin",
  "Delamanid",
  "Demeclocycline",
  "Dibekacin",
  "Dicloxacillin",
  "Difloxacin",
  "Dihydrostreptomycin",
  "Dirithromycin",
  "Doripenem",
  "Doxycycline",
  "Enoxacin",
  "Enrofloxacin",
  "Epicillin",
  "Eravacycline",
  "Ertapenem",
  "Erythromycin",
  "Ethambutol",
  "Ethionamide",
  "Faropenem",
  "Fidaxomicin",
  "Fleroxacin",
  "Flomoxef",
  "Florfenicol",
  "Flucloxacillin",
  "Flumequine",
  "Flurithromycin",
  "Formosulfathiazole",
  "Fosamil",
  "Fosfomycin",
  "Framycetin",
  "Furaltadone",
  "Furazidin",
  "Furazolidone",
  "Fusidic Acid",
  "Gamithromycin",
  "Gatifloxacin",
  "Gemifloxacin",
  "Gentamicin",
  "Grepafloxacin",
  "Hetacillin",
  "Hydriodide",
  "Ibafloxacin",
  "Iclaprim",
  "Imipenem",
  "Isepamicin",
  "Isoniazid",
  "Josamycin",
  "Kanamycin",
  "Kitasamycin",
  "Latamoxef",
  "Levofloxacin",
  "Lincomycin",
  "Linezolid",
  "Lomefloxacin",
  "Loracarbef",
  "Lymecycline",
  "Marbofloxacin",
  "Mecillinam",
  "Meropenem",
  "Meropenem/Vaborbactam",
  "Metacycline",
  "Metampicillin",
  "Methicillin",
  "Metronidazole",
  "Mezlocillin",
  "Midecamycin",
  "Minocycline",
  "Miocamycin",
  "Morinamide",
  "Moxifloxacin",
  "Mupirocin",
  "Nadifloxacin",
  "Nafcillin",
  "Nalidixic acid",
  "Neomycin",
  "Netilmicin",
  "Nifurtoinol",
  "Nitrofural",
  "Nitrofurantoin",
  "Norfloxacin",
  "Ofloxacin",
  "Oleandomycin",
  "Omadacycline",
  "Orbifloxacin",
  "Oritavancin",
  "Ornidazole",
  "Oxacillin",
  "Oxolinic acid",
  "Oxytetracycline",
  "Ozenoxacin",
  "Panipenem",
  "Para-aminosalicylic-acid",
  "Paromomycin",
  "Pazufloxacin",
  "Pefloxacin",
  "Penamecillin",
  "Penethamate",
  "Penimepicycline",
  "Pheneticillin",
  "Phenoxymethylpenicillin/Penicillin V",
  "Phthalylsulfathiazole",
  "Pipemidic acid",
  "Piperacillin",
  "Piperacillin-Tazobactam",
  "Pirlimycin",
  "Piromidic acid",
  "Pivampicillin",
  "Pivmecillinam",
  "Plazomicin",
  "Polymyxin B",
  "Pradofloxacin",
  "Pristinamycin",
  "Procaine Benzylpenicillin",
  "Propicillin",
  "Protionamide",
  "Prulifloxacin",
  "Pyrazinamide",
  "Pyrimethamine",
  "Quinupristin-dalfopristin",
  "Radezolid",
  "Ramoplanin",
  "Retapamulin",
  "Ribostamycin",
  "Rifabutin",
  "Rifampicin",
  "Rifamycin",
  "Rifapentine",
  "Rifaximin",
  "Rokitamycin",
  "Rolitetracycline",
  "Rosoxacin",
  "Roxithromycin",
  "Rufloxacin",
  "Secnidazole",
  "Sitafloxacin",
  "Sodium aminosalicylate",
  "Solithromycin",
  "Sparfloxacin",
  "Spectinomycin",
  "Spiramycin",
  "Streptomycin",
  "Sulbenicillin",
  "Sulfadiazine",
  "Sulfadimethoxine",
  "Sulfadimidine",
  "Sulfafurazole/Sulfisoxazole",
  "Sulfaisodimidine",
  "Sulfalene",
  "Sulfamazone",
  "Sulfamerazine",
  "Sulfamethizole",
  "Sulfamethoxazole",
  "Sulfamethoxypyridazine",
  "Sulfametomidine",
  "Sulfametoxydiazine",
  "Sulfametrole",
  "Sulfamoxole",
  "Sulfanilamide",
  "Sulfaperin",
  "Sulfaphenazole",
  "Sulfapyridine",
  "Sulfathiazole",
  "Sulfathiourea",
  "Sultamicillin",
  "Talampicillin",
  "Tazobactam",
  "Tedizolid",
  "Teicoplanin",
  "Telavancin",
  "Telithromycin",
  "Temafloxacin",
  "Temocillin",
  "Terizidone",
  "Tetracycline",
  "Tetroxoprim",
  "Thiamphenicol",
  "Tiamulin",
  "Ticarcillin",
  "Ticarcillin-Clavulanic-acid",
  "Tigecycline",
  "Tildipirosin",
  "Tilmicosin",
  "Tinidazole",
  "Tiocarlide",
  "Tobramycin",
  "Trimethoprim",
  "Troleandomycin",
  "Tulathromycin",
  "Tylosin",
  "Tylvalosin",
  "Valnemulin",
  "Vancomycin",
  "Virginiamycin"
];

